### ISSUE TITLE
TypeError: '_NamespacePath' object does not support indexing

### ISSUE THREAD

**Issue by ZhaoQi99** [ZhaoQi99/pyencrypt-pye#5]
报错如下
```python
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    from test.test2.abc import *
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "/Users/zhaoqi219/Code/python_encrypt/encrypted/loader.py", line 411, in find_spec
    file_path = Path(path[0]) / f'{fullname.rsplit(".",1)[-1]}.pye'
TypeError: '_NamespacePath' object does not support indexing
```
目录结构是
```shell
test
├── __init__.py
└── test2
    └── abc.py
```
代码是
```python
import loader
from test.test2.abc import *
```

**Comment by ZhaoQi99** [comment]
`test2`目录下不存在`__init__.py`文件时,传给`find_spec`函数的实参`path`是个`_NamespacePath`对象,而不是`list`

**Comment by ZhaoQi99** [comment]
> `test2`目录下不存在`__init__.py`文件时,传给`find_spec`函数的实参`path`是个`_NamespacePath`对象,而不是`list`

可通过`test2`目录下添加`__init__.py`文件解决问题
